export const pizzas = [
  {
    id: 1,
    name: 'Пепперони',
    category: 'meat',
    price: 289,
    rating: 4.8,
    imageUrl: '🍕',
    isNew: false,
    isSpicy: true,
  },
  {
    id: 2,
    name: 'Маргарита',
    category: 'cheese',
    price: 249,
    rating: 4.6,
    imageUrl: '🧀',
    isNew: true,
    isSpicy: false,
  },
  {
    id: 3,
    name: 'Чикен Барбекю',
    category: 'grill',
    price: 329,
    rating: 4.9,
    imageUrl: '🍗',
    isNew: false,
    isSpicy: false,
  },
  {
    id: 4,
    name: 'Вегетарианская',
    category: 'veg',
    price: 269,
    rating: 4.5,
    imageUrl: '🥦',
    isNew: false,
    isSpicy: false,
  },
  {
    id: 5,
    name: 'Мексиканская',
    category: 'spicy',
    price: 299,
    rating: 4.7,
    imageUrl: '🌶️',
    isNew: false,
    isSpicy: true,
  },
  {
    id: 6,
    name: '4 Сыра',
    category: 'cheese',
    price: 319,
    rating: 4.8,
    imageUrl: '🧀',
    isNew: true,
    isSpicy: false,
  },
  {
    id: 7,
    name: 'Карбонара',
    category: 'meat',
    price: 349,
    rating: 4.9,
    imageUrl: '🥓',
    isNew: false,
    isSpicy: false,
  },
  {
    id: 8,
    name: 'Гавайская',
    category: 'closed',
    price: 279,
    rating: 4.4,
    imageUrl: '🍍',
    isNew: false,
    isSpicy: false,
  },
];
